### ISSUE TITLE
Bugs in the codes

### ISSUE THREAD

**Issue by geekyutao** [khurramjaved96/mrcl#11]
Hi, thanks for your codes! It really helps me! But when I re-implement the Omniglot training expriment, there seems to be an error as following:
Traceback (most recent call last):
  File "oml_omniglot.py", line 100, in <module>
    main(args)
  File "oml_omniglot.py", line 71, in main
    accs, loss = maml(x_spt, y_spt, x_qry, y_qry)
  File "/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/mrcl/model/meta_learner.py", line 254, in forward
    fast_weights = self.inner_update(x_traj[k], fast_weights, y_traj[k], True)
IndexError: index 19 is out of bounds for dimension 0 with size 19

I cannot figure out the reason. Hope for your response.

**Comment by ok1zjf** [comment]
It really appears like a bug. The x_traj and y_traj are filled with self.update_step-1 items
https://github.com/khurramjaved96/mrcl/blob/9ec823336b9d86f847f188ebbda6d5be1d0bda4e/model/meta_learner.py#L72-L75
while here 
https://github.com/khurramjaved96/mrcl/blob/9ec823336b9d86f847f188ebbda6d5be1d0bda4e/model/meta_learner.py#L252-L254
are indexed from 1 till self.update_step.
I believe this could be fixed by setting the index to k-1
`fast_weights = self.inner_update(x_traj[k-1], fast_weights, y_traj[k-1], True)`

**Comment by geekyutao** [comment]
Thanks a lot！

**Comment by khurramjaved96** [comment]
Hi,
Adding self.update_step = len(x_traj) before meta_losses = [0 for _ in range(self.update_step)] should fix the issue for now. (Or you can use --update_step 10 during training).

I suspect some of the changes I made to the repo later have broken things. I have a cleaner implementation of the method that I'm using for my follow-up work. Hopefully, I'll update this repo with the new implementation someday.

**Comment by geekyutao** [comment]
Hi，
    Thanks for reminding! I have fixed it. I will continually follow your future updating.

Best
