### ISSUE TITLE
Truncated backprop through time

### ISSUE THREAD

**Issue by jlindsey15** [khurramjaved96/mrcl#16]
One other question I have: the paper mentions that the computation graph is never unrolled for more than a fixed number of steps, similar to truncated backprop through time.  I don't fully understand how this works, since some of the meta-parameters being optimized are the initial network weights, which by the time you are in the middle of the inner loop are no longer directly involved in the computation graph -- so I'm not clear on how you get a "truncated" gradient of the meta-loss with respect to these weights.  Would you be able to clarify how this works, or point to the place in the code that does it?

**Comment by jlindsey15** [comment]
If I understood things correctly, an older version of the paper and code used inner loops that only introduced one new class at a time, and allowed the classifier weights to also be meta-learned, so that the network would have some prior knowledge that it needed to avoid forgetting (and this necessitated a weight resetting procedure to prevent memorization).  This all made sense to me, but the newest arXiv paper seems to describe a different procedure.

**Comment by khurramjaved96** [comment]
> One other question I have: the paper mentions that the computation graph is never unrolled for more than a fixed number of steps, similar to truncated backprop through time. I don't fully understand how this works, since some of the meta-parameters being optimized are the initial network weights, which by the time you are in the middle of the inner loop are no longer directly involved in the computation graph -- so I'm not clear on how you get a "truncated" gradient of the meta-loss with respect to these weights. Would you be able to clarify how this works, or point to the place in the code that does it?

I wouldn't say that the initial weights are not involved in the computation graph in the middle of inner loop. Let \theta and \W_k be the meta-parameters and adaptation parameters at the kth update for data-point (x_k, y_k). Because \theta is used to get the representation for x_k, it is still involved in the computation graph. 

The truncated aspect in implemented using the way I sample data for inner and meta update.. Because I evaluate the method for up-to 200 classes, the correct gradients would have to be computed by doing inner updates for all 200 classes. However, I only use 5-10 classes for each meta-update. Another way of looking at sampling 5 classes is that I'm still doing inner updates for all 200 classes, but truncating gradients after 5 classes.

The underlying assumption in this approximation is that if a representation is good for learning 10 classes incrementally, the same representation is good for learning 200 classes as well. This seems to hold in the the simple benchmark I have, but would be problematic for settings that have temporal dependencies across time -- such as delayed reward in RL settings.

**Comment by jlindsey15** [comment]
Thanks -- just want to make sure I understand, could you clarify which of the following is being done (or neither)?

 Option 1: you sample 5 classes, do inner updates, backpropagate meta-loss, update meta-parameters, then sample the next 5 classes and start _fresh with the updated meta-parameters._. 

Option 2 (how I interpreted "truncation"): you do inner updates, backpropagate meta-loss, store these gradients somewhere for accumulation, then sample the next 5 classes but continue to build on the adapted weights from your existing inner loop.  Then, only _after_ the whole 200-step inner loop, you combine all your accumulated gradients and use them to update the meta-parameters.

**Comment by khurramjaved96** [comment]
> If I understood things correctly, an older version of the paper and code used inner loops that only introduced one new class at a time, and allowed the classifier weights to also be meta-learned, so that the network would have some prior knowledge that it needed to avoid forgetting (and this necessitated a weight resetting procedure to prevent memorization). This all made sense to me, but the newest arXiv paper seems to describe a different procedure.

That is correct. I replaced the old method because it was too specific to learning incremental classifiers even though I see OML as a more general algorithm. Instead of reseting the weights of the classifier, we can just make the targets non-stationary -- in every meta-update, different classes can have the same target. This takes care of the memorization issue without using any tricks that are only applicable for classifiers. Few-shot learning methods also avoid memorization by making targets non-stationary (In every update in MAML, target 1 can correspond to a different class). 

The newer implementation is also not completely faithful to the pseudocode in the paper. I'm currently writing all the work -- some published and some follow-up to OML -- as my thesis and plan to release a more consistent implementation of OML once I'm done (End of September).

**Comment by khurramjaved96** [comment]
> Thanks -- just want to make sure I understand, could you clarify which of the following is being done (or neither)?

Option 1. The pseudocode in the appendix of the paper also implements something close to option 1 (In line 13, the meta-parameters are updated every m steps)

**Comment by jlindsey15** [comment]
Got it, thanks!  Sorry, to keep peppering you with questions, but I have one more based on your last comment.  When you say "make the targets non-stationary," I assume you mean that for each inner loop you randomly permute the labels corresponding to each image class?  That makes sense to me for vanilla MAML.  But for OML it seems like a problem: in this implementation, shouldn't the performance of the network be at chance at the beginning of each inner loop?  How is the network incentivized to "avoid forgetting" if it isn't already performing well at the start of (at least some) inner loops?
